apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-price-mlops
  template:
    metadata:
      labels:
        app: house-price-mlops
    spec:
      containers:
        - name: name
          image: 551183203355.dkr.ecr.ap-south-1.amazonaws.com/house-price-mlops:latest
          ports:
            - containerPort: 8000
