apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-price-mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-price
  template:
    metadata:
      labels:
        app: house-price
    spec:
      containers:
        - name: ml-container
          image: <ECR_URI>:latest
          ports:
            - containerPort: 8000
