apiVersion: v1
kind: Service
metadata:
  name: house-price-mlops-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: "/"
spec:
  type: LoadBalancer
  selector:
    app: house-price-mlops
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
